import type { LineupPlayer, MatchEvent, MatchStats, OpponentSetup, Player, PlayerRating, Tactics, TacticalSetup, Team, SimulationContext, SimulationResult } from '../types';

const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
const avg=(a:number[])=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
function seededRandom(seed:number){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let r=Math.imul(t^t>>>15,1|t);r^=r+Math.imul(r^r>>>7,61|r);return((r^r>>>14)>>>0)/4294967296;};}
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0;}

export function simulateMatch(team:Team,opponent:Team,setup:TacticalSetup,opp:OpponentSetup,players:Player[],nonce=0,context?:SimulationContext):SimulationResult{
 const simulationContext=context??defaultContext();
 const ours=players.filter(p=>setup.players.some(x=>x.playerId===p.id));
 const oppTeamStrength=Math.max(68,Math.min(92,opponent.rating/20));
 const g=seededRandom(hash(`${team.id}|${opponent.id}|${setup.formation}|${JSON.stringify(setup.tactics)}|${simulationContext.year}|${simulationContext.mode}|${nonce}`));
 const attack=avg(ours.filter(p=>p.position==='FWD').map(p=>p.rating))||74;
 const midfield=avg(ours.filter(p=>p.position==='MID').map(p=>p.rating))||74;
 const defence=avg(ours.filter(p=>p.position==='DEF').map(p=>p.rating))||74;
 const goalkeeper=avg(ours.filter(p=>p.position==='GK').map(p=>p.rating))||74;
 const tacticalFit=roleFit(setup.players,ours,setup.tactics);
 const oppAttack=oppTeamStrength*(opp.preset==='High Press'?1.01:opp.preset==='Low Block'?.92:1);
 const possessionBase=50+(midfield-oppTeamStrength)*.55+(setup.tactics.possession-50)*.18+(setup.tactics.pressing-opp.tactics.pressing)*.07+(team.rating-opponent.rating)/70;
 const possession0=clamp(possessionBase+(g()-.5)*4,30,70),p0=Math.round(possession0),possession:[number,number]=[p0,100-p0];
 const counterBoost=Math.max(0,opp.tactics.defensiveLine-60)*.012+Math.max(0,opp.tactics.attackingRisk-55)*.008;
 const pressRisk=setup.tactics.pressing*.012+setup.tactics.defensiveLine*.009+setup.tactics.attackingRisk*.007;
 const chanceQuality=clamp(attack*.022+tacticalFit*.18+setup.tactics.tempo*.004+setup.tactics.attackingRisk*.004+setup.tactics.width*.0015+counterBoost-pressRisk*.15,.6,3.2);
 const oppChanceQuality=clamp(oppAttack*.018+opp.tactics.tempo*.003+opp.tactics.attackingRisk*.004+Math.max(0,setup.tactics.defensiveLine-60)*.008+Math.max(0,setup.tactics.attackingRisk-60)*.009-defence*.008-goalkeeper*.002,.55,2.8);
 const shots:[number,number]=[Math.round(clamp(7+possession[0]*.075+setup.tactics.tempo*.045+setup.tactics.attackingRisk*.04+attack*.02+(g()-.5)*2,7,23)),Math.round(clamp(7+possession[1]*.07+opp.tactics.tempo*.04+opp.tactics.attackingRisk*.045+oppAttack*.018+(100-setup.tactics.defensiveLine)*.015+(g()-.5)*2,6,21))];
 const xg:[number,number]=[round2(shots[0]*chanceQuality/18),round2(shots[1]*oppChanceQuality/18)];
 const score:[number,number]=[boundedPoisson(xg[0],g),boundedPoisson(xg[1],g)];
 const onTarget:[number,number]=[clamp(Math.round(shots[0]*(.27+chanceQuality*.035+g()*.07)),1,shots[0]),clamp(Math.round(shots[1]*(.25+oppChanceQuality*.035+g()*.07)),1,shots[1])];
 const highTurnovers:[number,number]=[Math.round(3+setup.tactics.pressing*.1+Math.max(0,opp.tactics.possession-60)*.02),Math.round(2.5+opp.tactics.pressing*.08+(100-setup.tactics.possession)*.02)];
 const stats:MatchStats={possession,shots,shotsOnTarget:onTarget,xg,dangerousAttacks:[Math.round(shots[0]*1.65+setup.tactics.attackingRisk*.08),Math.round(shots[1]*1.55+opp.tactics.attackingRisk*.08)],highTurnovers,bigChances:[Math.max(score[0],Math.round(xg[0]*.75+g()*.8)),Math.max(score[1],Math.round(xg[1]*.7+g()*.8))],fouls:[Math.round(7+setup.tactics.pressing*.05+g()*4),Math.round(7+opp.tactics.pressing*.05+g()*4)],corners:[Math.round(3+shots[0]*.18+setup.tactics.width*.018),Math.round(3+shots[1]*.18+opp.tactics.width*.014)]};
 const events=makeEvents(score,stats,g,setup,opp);const ratings=makeRatings(ours,setup,score[0],g);ratings.sort((a,b)=>b.rating-a.rating);
 const verdict=makeReport(team.name,opponent.name,stats,setup.tactics,opp.tactics,setup.formation,midfield,attack,defence);
 const assumptions=[...simulationContext.assumptions,'Team and player ratings are app-model inputs, not official historical ratings.','Match events, score, xG, player ratings and tactical verdicts are model-generated; they are not historical match records.'];
 return{score,stats,events,ratings,playerOfMatch:ratings[0]?.playerId??ours[0]?.id??'',verdict:verdict.slice(0,3),tacticalEdge:verdict.slice(3),assumptions,context:simulationContext,seed:hash(`${team.id}|${opponent.id}|${simulationContext.year}|${nonce}`)};
}
function defaultContext():SimulationContext{return{year:2026,mode:'current',competition:'FIFA World Cup 2026',dataBasis:'2026 final-squad dataset plus app tactical model',assumptions:['The simulation is hypothetical and does not reproduce a recorded World Cup match.','The rules-based engine uses the selected formation, tactics, app ratings and opponent preset.']};}

function roleFit(lineup:LineupPlayer[],players:Player[],t:Tactics){const v=lineup.reduce((s,l)=>{const p=players.find(x=>x.id===l.playerId);if(!p)return s;let f=0;if(l.role.includes('Playmaker')||l.role.includes('Midfielder'))f+=t.possession*.01;if(l.role.includes('Winger'))f+=t.width*.006;if(l.role.includes('Forward'))f+=t.attackingRisk*.006;if(l.role.includes('Keeper'))f+=(100-t.defensiveLine)*.002;return s+f;},0);return clamp(v/Math.max(1,lineup.length),0,1);}
function round2(n:number){return Math.round(n*100)/100;}
function boundedPoisson(lambda:number,r:()=>number){let k=0,p=1,L=Math.exp(-Math.min(lambda,3.5));do{k++;p*=r();}while(p>L&&k<6);return Math.min(5,k-1);}
function makeEvents(score:[number,number],stats:MatchStats,r:()=>number,setup:TacticalSetup,opp:OpponentSetup){const out:MatchEvent[]=[];for(const side of [0,1] as const)for(let i=0;i<score[side];i++){const min=10+Math.floor(r()*78);const text=side===0?(setup.tactics.pressing>65?'High turnover creates a quick finish.':'Combination play opens the final third.'):(opp.tactics.defensiveLine>65?'Counterattack into space behind the line.':'Patient build-up finds a gap.');out.push({minute:min,team:side,type:'goal',text});}const yellows=Math.min(4,Math.round((stats.fouls[0]+stats.fouls[1])/18));for(let i=0;i<yellows;i++)out.push({minute:20+Math.floor(r()*65),team:(i%2) as 0|1,type:'yellow',text:'Late challenge stops a developing attack.'});if(stats.bigChances[0]>score[0])out.push({minute:Math.round(25+r()*45),team:0,type:'chance',text:'Big chance created from sustained pressure.'});if(stats.bigChances[1]>score[1])out.push({minute:Math.round(35+r()*40),team:1,type:'chance',text:'Big chance on the break.'});return out.sort((x,y)=>x.minute-y.minute).slice(0,9);}
function makeRatings(players:Player[],setup:TacticalSetup,goals:number,r:()=>number):PlayerRating[]{return players.map(p=>{const l=setup.players.find(x=>x.playerId===p.id);let v=p.rating/10;if(l){if(l.role.includes('Winger')||l.role.includes('Forward'))v+=setup.tactics.attackingRisk*.009;if(l.role.includes('Playmaker'))v+=setup.tactics.possession*.006;if(l.role.includes('Back'))v+=(100-setup.tactics.defensiveLine)*.003;if(l.role.includes('Press'))v+=setup.tactics.pressing*.004;}v+=(r()-.5)*.7;if(goals&&(p.position==='FWD'||p.position==='MID'))v+=goals*.15;return{playerId:p.id,rating:clamp(round2(v),5.8,9.7),contribution:v>8.3?'Influential':v>7.6?'Strong':'Useful'};});}
function makeReport(team:string,opp:string,s:MatchStats,t:Tactics,ot:Tactics,formation:string,midfield:number,attack:number,defence:number){const lines:string[]=[];lines.push(s.possession[0]>54?`${team}'s midfield control delivered a ${s.possession[0]}% possession share.`:`${team} played without dominating the ball, so the match depended on transition moments.`);lines.push(t.pressing>65?`The aggressive press produced ${s.highTurnovers[0]} high turnovers, but it increased exposure behind the defensive line.`:`The pressing block stayed measured, keeping the defensive shape compact.`);lines.push(t.defensiveLine>68&&ot.attackingRisk>60?`${opp}'s attacking risk created space in transition against the higher line.`:t.attackingRisk>68?`The attacking risk added bodies forward and raised chance volume from the ${formation}.`:`The ${formation} maintained a balanced rest-defence while still generating chances.`);if(s.corners[0]>s.corners[1])lines.push(`Width helped ${team} pin ${opp} back and win ${s.corners[0]} corners.`);else lines.push(`${opp}'s shape limited central progression and forced ${team} into lower-value wide attacks.`);if(midfield>attack)lines.push('The strongest tactical lever was control in midfield rather than pure finishing.');else lines.push('The biggest edge came from the front line\'s ability to convert possession into shots.');if(defence<72)lines.push(`The defensive unit remained the clearest pressure point when ${opp} attacked early.`);return lines;}
